### PR TITLE
Initial implementation of a few control parameters

### PR DESCRIPTION
**Pull request by phikal**
As mentioned in #4, this is a first attempt at implementing a few control parameters.

I'm not quite satisfied with the pull request, as it is, hence the draft status.  My main annoyance is that not all keyword arguments are used, depending on the "implicit" usage of integer variables. I was thinking if it would be better to split `glpk-solver` into a simplex solver and an integer solver, each with only the necessary/useful keywords.

Another issue was that I wasn't certain what error to signal when GLPK returns with `:no-feasible-solution-exists`, as opposed to `:infeasible`.

### CODE REVIEW

**Comment by neil-lindquist** [comment]
That looks like a good start (and good catch on the ffi fixes).

I was expecting that there would be keywords that aren't always relevant and don't feel it's a major issue.  I wrote the generic-solver API in linear-programming with the thought that backends would ignore unused options.  But, I'm open to suggestions if you think there are specific issues with the design.

I had a couple more options in mind that I think would be beneficial, but feel free to ignore them if you don't want to work on them.
* First is using the interior-point solver instead of simplex (for non-integer problems).
* Second is adding verbosity support.  I have some thoughts about cross-backend portability here, so if you're interested, let me know and I can share my thoughts.

I think both return codes (`:no-feasible-solution-exists` and `:infeasible`) can use the same error.  I think the later comes from certain use cases where you're trying to adjust an infeasible solution until it's feasible again.
Although, you appear to be checking the codes from `%get-status` and friends (`solution-status`) instead of the return codes from the solvers (`solver-exit-code`).

One final recommendation: you may want to consider using [`supplied-p-parameter`s](http://www.lispworks.com/documentation/HyperSpec/Body/03_da.htm) to only set values in the control structure if the caller passed the keyword.  At a minimum I'd recommend changing the defaults to match the defaults listed in the GLPK manual (pages 41-42 and 60-63).

**Comment by phikal** [comment]
>  But, I'm open to suggestions if you think there are specific issues with the design.

I think the design is fine, I just worry that people might be confused why, eg. `:preprocessing-technique` has no effect (if they haven't read the manual). Then again, using the `linear-programming` interface, even with SLIME they wouldn't know what arguments exist, and the user would have to rely on external documentation anyway.

> First is using the interior-point solver instead of simplex (for non-integer problems).

I could add support for that, next to simplex and integer. But I think at least adding a `:method` keyword wouldn't be bad, unless that breaks some abstraction you had in mind.

> Second is adding verbosity support. I have some thoughts about cross-backend portability here, so if you're interested, let me know and I can share my thoughts.

I disabled it, because I think libraries shouldn't just write to stdout, but that was more of an opinionated choice.

>  Although, you appear to be checking the codes from %get-status and friends (solution-status) instead of the return codes from the solvers (solver-exit-code).

Oops, you're right, I'll fix that.

> One final recommendation: you may want to consider using supplied-p-parameters to only set values in the control structure if the caller passed the keyword. At a minimum I'd recommend changing the defaults to match the defaults listed in the GLPK manual (pages 41-42 and 60-63).

That's what I was currently doing (or I at least hope that). I was setting the values unconditionally, so that even if GLPK changes, the library's behaviour tries to stay the same.

**Comment by neil-lindquist** [comment]
> I just worry that people might be confused why, eg. :preprocessing-technique has no effect ...

That's a fair point.  Although, I think it shouldn't be too much of an issue since, like you said, the main linear-programming interface hides it and these are mostly expert level optimizations for hard problems.
We could maybe consider raising warnings if the caller passes arguments unused for a method (maybe for certain levels of verbosity?)

> But I think at least adding a :method keyword wouldn't be bad

That what I was thinking (at least for the choice between interior-point versus simplex).  The decision is how to address the case where integer-variables are present.
1. It could be a suggestion that's ignored for the integer case
2. An error or warning could be raised for trying to use interior-point for integer problems
3. The method option could have integer as a third choice, and make the caller indicate whether they have an integer or continuous problem

> I disabled it, because I think libraries shouldn't just write to stdout, but that was more of an opinionated choice.

I agree that the default should be not-verbose.  It'd be an opt-in feature for users who want to monitor the progress on large problems.

>That's what I was currently doing (or I at least hope that).

According to the manual I have for GLPK 4.65, the defaults for pricing and ratio-test are projected steepest edge (`GLP_PT_PSE`) and Harris' two-pass ratio test (`GLP_RT_HAR`), respectively, while you have the default as standard (`GLP_PT_STD` / `GLP_RT_STD`) for both.  The rest the the defaults match though.

**Comment by phikal** [comment]
Sorry for the delay, here's an initial suggestion to fix the issues you raised. My proposed solution to the `:method` question is to only raise an error, if it was explicitly set, and "ignore" unnecessary parameters if it was "guessed".

**Comment by neil-lindquist** [comment]
That seems like a good approach.

For logging, I think it might be more intuitive to use commonly used log level names, plus `t` and `nil` as CL's usual verbosity arguments.  It'd also simplify cross-backend portability, since I'm looking at adding at least a little logging to the CL backend.  It could be converted to GLPK's options with something like:
```common-lisp
(ecase message-level
  ((nil :off) :off)
  ((:error :warn) :error)
  ((t :info) :on)
  (:debug :all))
```
(I skipped GLPK's debug level, since that appears to be for debugging GLPK itself)

**Comment by phikal** [comment]
Makes sense, but couldn't aliasing `:debug` to `:all` confuse people who have already had used GLPK?

**Comment by neil-lindquist** [comment]
That's a fair point.  The debug level doesn't appear in the manual as far as I can tell, so this issue would be specifically limited to people who've spent time reading the sources.  My gut feeling is that the overlap between that group and people who'd use the CL interface will be negligible, but I'm not really sure.

**Comment by phikal** [comment]
I've added your suggested code, and all in al, I think you're right. I'll de-draft the pull request now, and write a few tests.

**Comment by neil-lindquist** [comment]
I started working on tests a few days ago, and just pushed what I have so far.

**Comment by phikal** [comment]
The last few commits made your tests pass, I'll add a few more in another pull request.

**Comment by phikal** [comment]
It seems the `message-level` property doesn't change anything. Internally, it uses a function named [`glp_puts`](https://github.com/firedrakeproject/glpk/blob/45156a549252849cad016366022aa1af50990613/src/env/stdout.c#L39), that is supposed to write to stdout, but I can't find much online on how CFFI handles this situation. It doesn't seem like flushing is the issue, because `glp_puts` flushes immediately.

**Comment by neil-lindquist** [comment]
Are you using SLIME (or another IDE based on a swank/slynk server)?  There's some redirection of output streams in the swank server that might not be redirecting the stdout that FFI sees.

**Comment by phikal** [comment]
I am, I'll look into if that's the cause.

**Comment by phikal** [comment]
The messages are apparently displayed in the `*inferior-lisp*` buffer.

**Pull request merged**
